#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-worrms
Version  : 0.3.2
Release  : 8
URL      : https://cran.r-project.org/src/contrib/worrms_0.3.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/worrms_0.3.2.tar.gz
Summary  : World Register of Marine Species (WoRMS) Client
Group    : Development/Tools
License  : MIT
Requires: R-crul
Requires: R-data.table
Requires: R-jsonlite
Requires: R-tibble
Requires: R-vcr
BuildRequires : R-crul
BuildRequires : R-data.table
BuildRequires : R-jsonlite
BuildRequires : R-tibble
BuildRequires : R-vcr
BuildRequires : buildreq-R

%description
worrms
======
[![Project Status: Active â The project has reached a stable, usable state and is being actively developed.](https://www.repostatus.org/badges/latest/active.svg)](https://www.repostatus.org/#active)
[![cran checks](https://cranchecks.info/badges/worst/worrms)](https://cranchecks.info/pkgs/worrms)
[![Build Status](https://travis-ci.org/ropensci/worrms.svg?branch=master)](https://travis-ci.org/ropensci/worrms)
[![Build status](https://ci.appveyor.com/api/projects/status/e5q7fi97pl49h7v6?svg=true)](https://ci.appveyor.com/project/sckott/worrms)
[![codecov](https://codecov.io/gh/ropensci/worrms/branch/master/graph/badge.svg)](https://codecov.io/gh/ropensci/worrms)
[![rstudio mirror downloads](http://cranlogs.r-pkg.org/badges/worrms)](https://github.com/metacran/cranlogs.app)
[![cran version](http://www.r-pkg.org/badges/version/worrms)](https://cran.r-project.org/package=worrms)

%prep
%setup -q -c -n worrms

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1546662120

%install
export SOURCE_DATE_EPOCH=1546662120
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library worrms
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library worrms
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library worrms
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library worrms|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/worrms/DESCRIPTION
/usr/lib64/R/library/worrms/INDEX
/usr/lib64/R/library/worrms/LICENSE
/usr/lib64/R/library/worrms/Meta/Rd.rds
/usr/lib64/R/library/worrms/Meta/features.rds
/usr/lib64/R/library/worrms/Meta/hsearch.rds
/usr/lib64/R/library/worrms/Meta/links.rds
/usr/lib64/R/library/worrms/Meta/nsInfo.rds
/usr/lib64/R/library/worrms/Meta/package.rds
/usr/lib64/R/library/worrms/Meta/vignette.rds
/usr/lib64/R/library/worrms/NAMESPACE
/usr/lib64/R/library/worrms/NEWS.md
/usr/lib64/R/library/worrms/R/worrms
/usr/lib64/R/library/worrms/R/worrms.rdb
/usr/lib64/R/library/worrms/R/worrms.rdx
/usr/lib64/R/library/worrms/doc/index.html
/usr/lib64/R/library/worrms/doc/worrms_vignette.Rmd
/usr/lib64/R/library/worrms/doc/worrms_vignette.html
/usr/lib64/R/library/worrms/help/AnIndex
/usr/lib64/R/library/worrms/help/aliases.rds
/usr/lib64/R/library/worrms/help/paths.rds
/usr/lib64/R/library/worrms/help/worrms.rdb
/usr/lib64/R/library/worrms/help/worrms.rdx
/usr/lib64/R/library/worrms/html/00Index.html
/usr/lib64/R/library/worrms/html/R.css
